spring:
  profiles:
    active: dev

---
spring:
  application:
    name: consumer-demo
  config:
    activate:
      on-profile:
        - dev

server:
  port: 10010

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map:
      zone: zone-1
  client:
    register-with-eureka: false
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: guangzhou
    availability-zones:
      guangzhou: zone-1
    service-url:
      defaultZone: http://localhost:8761/eureka/
      zone-1: http://localhost:8761/eureka/